//login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const FACILITY_CHANGE_SUCCESS = "FACILITY_CHANGE_SUCCESS";
export const LOGOUT = "LOGOUT";


export const GO_TO_IN_CART = "GO_TO_IN_CART";
export const FETCH_OUT_CART_ORDERS= "FETCH_OUT_CART_ORDERS";
export const SELECT_MEAL_ORDER= "SELECT_MEAL_ORDER";
export const UNSELECT_MEAL_ORDER= "UNSELECT_MEAL_ORDER";
export const FETCH_CARTS= "FETCH_CARTS";
export const ADD_TO_CART= "ADD_TO_CART";
export const FETCH_KITCHENS= "FETCH_KITCHENS";
export const SELECT_KITCHEN= "SELECT_KITCHEN";
export const FETCH_UNITS= "FETCH_UNITS";
export const REMOVE_TRAY_FROM_CART= "REMOVE_TRAY_FROM_CART";
export const DELETE_CART= "DELETE_CART";
export const FETCH_SERVICE_STYLES = "FETCH_SERVICE_STYLES";
export const OPEN_INCART_SUMMARY = "OPEN_INCART_SUMMARY";
export const SHOW_CART_ALREADY_EXISTS_MESSAGE = "SHOW_CART_ALREADY_EXISTS_MESSAGE";
export const CLOSE_ALERT_MESSAGE = "CLOSE_ALERT_MESSAGE";
export const REMOVE_FROM_OUT_CART_ORDERS = "REMOVE_FROM_OUT_CART_ORDERS";
export const UPDATE_SELECTED_SORT_BY = "UPDATE_SELECTED_SORT_BY";
export const UPDATE_SELECTED_MEAL_NAME = "UPDATE_SELECTED_MEAL_NAME";
export const UPDATE_SELECTED_SERVICE_STYLE = "UPDATE_SELECTED_SERVICE_STYLE";
export const UPDATE_SELECTED_KITCHEN = "UPDATE_SELECTED_KITCHEN";
export const UPDATE_SELECTED_UNIT = "UPDATE_SELECTED_UNIT";
export const FETCH_FACILITY_MEAL_NAMES = "FETCH_FACILITY_MEAL_NAMES";
export const CLEAR_INCART_FILTERS = "CLEAR_INCART_FILTERS";
export const FILTER_OUT_CART_ORDERS = "FILTER_OUT_CART_ORDERS";

//For departed screen
export const READY_TO_DEPART_CARTS = "READY_TO_DEPART_CARTS";
export const OPEN_CART_SUMMARY = "OPEN_CART_SUMMARY"; 
export const CLOSE_CART_SUMMARY = "CLOSE_CART_SUMMARY";
export const ADD_TRAYS = "ADD_TRAYS";
export const REMOVE_ADDED_OUT_CART_ORDERS = "REMOVE_ADDED_OUT_CART_ORDERS";
export const ADD_TO_COMPLETED_CART = "ADD_TO_COMPLETED_CART";
export const REMOVE_TRAY_FROM_DEPART_CART = "REMOVE_TRAY_FROM_DEPART_CART";
export const MARK_CART_DEPARTED_SUCCESS = "MARK_CART_DEPARTED_SUCCESS";
export const HIDE_CONFIRMATION = "HIDE_CONFIRMATION";
export const FILTER_DEPART_CARTS = "FILTER_DEPART_CARTS";
export const FETCH_SERVICE_STYLES_AND_KITCHENS = "FETCH_SERVICE_STYLES_AND_KITCHENS";
export const FILTER_KITCHENS_FOR_SELECTED_SERVICE_STYLE = "FILTER_KITCHENS_FOR_SELECTED_SERVICE_STYLE";

//For High Risk Tray Check Screen
export const READY_TO_HIGH_RISK_TRAY_CHECK_CARTS = "READY_TO_HIGH_RISK_TRAY_CHECK_CARTS";
export const REMOVE_TRAY_FROM_HIGH_RISK_CHECK_CART = "REMOVE_TRAY_FROM_HIGH_RISK_CHECK_CART";
export const MARK_CART_CHECKED_SUCCESS = "MARK_CART_CHECKED_SUCCESS";
export const HIDE_ERROR_MESSAGE = "HIDE_ERROR_MESSAGE";
export const FILTER_HIGH_RISK_CARTS = "FILTER_HIGH_RISK_CARTS";
export const FETCH_HIGH_RISK_SERVICE_STYLES_KITCHENS = "FETCH_HIGH_RISK_SERVICE_STYLES_KITCHENS";
export const SORT_AND_FILTER_HIGH_RISK_TRAYS = "SORT_AND_FILTER_HIGH_RISK_TRAYS";
export const HIGH_RISK_FILTER_KITCHENS = "HIGH_RISK_FILTER_KITCHENS";

//for Delivered Screen

export const READY_TO_DELIVER_CARTS = "READY_TO_DELIVER_CARTS";
export const UPDATE_TRAY_DELIVERED = "UPDATE_TRAY_DELIVERED";
export const UPDATE_DELIVERED_SUCCESS = "UPDATE_DELIVERED_SUCCESS";
export const UPDATE_UNDO_DELIVERED_SUCCESS = "UPDATE_UNDO_DELIVERED_SUCCESS";
export const SORT_AND_FILTER_TRAYS = "SORT_AND_FILTER_TRAYS"

//for Recovered Screen

export const FETCH_TRAYS_TO_RECOVER = "FETCH_TRAYS_TO_RECOVER";
export const RECOVER_TRAY = "RECOVER_TRAY";

//for loader
export const LOADING = "LOADING";
export const LOADING_SCREEN = "LOADING_SCREEN";

//switch facility
export const FETCH_FACILITY_SUCCESS = "FETCH_FACILITY_SUCCESS";
export const SAVE_FACILITY_SUCCESS = "SAVE_FACILITY_SUCCESS";
export const CLOSE_FACILITY_POPUP = "CLOSE_FACILITY_POPUP";
export const OFFLINE_SWITCH_FACILITY = "OFFLINE_SWITCH_FACILITY";

//offline indicator
export const UPDATE_NETWORK_STATE = "UPDATE_NETWORK_STATE";

//unit delivery action
export const FETCH_DELIVERY_OR_RECOVERY_UNITS = "FETCH_DELIVERY_OR_RECOVERY_UNITS";
export const UPDATE_UNIT_DELIVERED_FAIL = "UPDATE_UNIT_DELIVERED_FAIL";
export const UPDATE_UNIT_UNDO_DELIVERED_FAIL = "UPDATE_UNIT_UNDO_DELIVERED_FAIL"
export const RESET_UNIT_DELIVERY_FAIL_PARAMETERS = "RESET_UNIT_DELIVERY_FAIL_PARAMETERS";
export const UPDATE_SELECTED_KITCHEN_FOR_UNIT_DELIVERY = "UPDATE_SELECTED_KITCHEN_FOR_UNIT_DELIVERY";
export const CLEAR_UNIT_DELIVERY_FILTER = "CLEAR_UNIT_DELIVERY_FILTER";
export const GET_UNIT_DELIVERY_INITIAL_STATE = "GET_UNIT_DELIVERY_INITIAL_STATE";
export const UPDATE_SELECTED_KITCHEN_FOR_UNIT_RECOVERY = "UPDATE_SELECTED_KITCHEN_FOR_UNIT_RECOVERY";
